server:
  port: 7200
  
spring:
  cloud:
    config:
      discovery:
        enabled: true

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:7000/eureka/

feign:
  hystrix:
    enabled: true