server:
  port: 7000
  
spring:
  cloud:
    config:
      discovery:
        enabled: true
        serviceId: configserver7300
  
eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/